export const FETCH_ITEM_DATA = "FETCH_ITEM_DATA";
export const PARSE_ITEM_DATA = 'PARSE_ITEM_DATA';
export const PARSE_PROFESSION_ITEMS = 'PARSE_PROFESSION_ITEMS';
export const SAVE_USER_PREFERENCES = 'SAVE_USER_PREFERENCES';
export const GET_USER_PREFERENCES = 'GET_USER_PREFERENCES';