export const FETCH_ITEM_DATA = "FETCH_ITEM_DATA";
export const GET_USER_PREFERENCES = 'GET_USER_PREFERENCES';
export const ITEMS_ERROR = 'ITEMS_ERROR';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_MESSAGE = 'ITEMS_MESSAGE';
export const PARSE_ITEM_DATA = 'PARSE_ITEM_DATA';
export const PARSE_PROFESSION_ITEMS = 'PARSE_PROFESSION_ITEMS';
export const SAVE_USER_PREFERENCES = 'SAVE_USER_PREFERENCES';